<?php
/**
 * Country
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * tradewatch.io
 *
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Country Class Doc Comment
 *
 * @category Class
 * @description The country associated with the symbol (see ISO 3166-1 alpha-2)
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Country
{
    /**
     * Possible values of this enum
     */
    public const FR = 'fr';

    public const US = 'us';

    public const DE = 'de';

    public const NZ = 'nz';

    public const NL = 'nl';

    public const UK = 'uk';

    public const ES = 'es';

    public const CN = 'cn';

    public const CH = 'ch';

    public const GR = 'gr';

    public const BE = 'be';

    public const PT = 'pt';

    public const IT = 'it';

    public const ALL = 'all';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FR,
            self::US,
            self::DE,
            self::NZ,
            self::NL,
            self::UK,
            self::ES,
            self::CN,
            self::CH,
            self::GR,
            self::BE,
            self::PT,
            self::IT,
            self::ALL
        ];
    }
}


